defaults:
  - default
  - override data: stackoverflow
  - override model: model-100k
  - _self_

model:
  depth: 5
  dim_k: 12
  dropout: 0.46
  monotonic_bins: 10
data:
  batch_size: 204
optim:
  optimizer:
    lr: 0.0004
