defaults:
  - default
  - override data: harmonic
  - override model: model-100k-PropertyMTPP
  - _self_

data:
  batch_size: 140
model:
  conditioning_network:
    window_size: 200
    depth: 6
    dropout: 0.15
  monotonic_network:
    _target_: flex_tpp.invertible_1d.GMM1D
    bins: null
    num_components: 1
    dropout: 0.0
    fix_std: true
  dropout: 0.2
  dim_k: 24
  depth: 7
optim:
  optimizer:
    lr: 0.001
